reportSchedule: "0 27 17 * * *"
monitorRate: 10 # in seconds
hystrix:
  collapser.default.maxRequestsInBatch: 1
  collapser.default.requestCache.enabled: false

  command:
    requestWorkers:
      circuitBreaker.requestVolumeThreshold: 2 # do not change
      #circuitBreaker.errorThresholdPercentage: 99 It seems that we don't need thi parameter
      #metrics.rollingPercentile.enabled: false
      circuitBreaker.sleepWindowInMilliseconds: 900 # do not change
      execution.isolation.thread.timeoutInMilliseconds: 10000
      metrics.rollingStats.timeInMilliseconds: 500 # Why it should be so small?? for infrequent404 to work
      #metrics.rollingStats.numBuckets: 1

rules:
  - worker: "user.worker1"
    threshold: 3000000
  - worker: "pak1.test"
    threshold: 3000000
