antpool:
  url: "https://antpool.com/api/workers.htm"
telegram:
  timeout: 10 # in seconds
reportSchedule: "0 27 17 * * *"
monitorRate: 10 # in seconds
spring:
  application:
    name: "AntpoolMonitor"
  profiles:
    include: 'secrets'
