antpool:
  url: "https://antpool.com/api/workers.htm"
telegram:
  timeout: 10 # in seconds
reportSchedule: "0 0 11 * * *" # Cron-like syntax. See https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html
monitorRate: 600 # in seconds
spring:
  application:
    name: "AntpoolMonitor"
  profiles:
    include: 'secrets'
hystrix:
  command:
    requestWorkers:

      # amount of failed requests that will stop requests to the pool
      circuitBreaker.requestVolumeThreshold: 2

      # Sleep time for which requests will not be sent to the pool
      circuitBreaker.sleepWindowInMilliseconds: 1800000
      execution.isolation.thread.timeoutInMilliseconds: 10000

      # Time window for which the amount of failed requests is calculated
      metrics.rollingStats.timeInMilliseconds: 3600000
