antpool:
  key: "key"
  secret: "secret"
  user: "user" # Use antpool sub-account here. All your miners should be named user.minerName
telegram:
  apiKey: "apiKey"
  chatId: "chatId" # Chat or user Id where bot will send notifications
rules:
  - worker: "user.miner1"
    threshold: 3000000
  - worker: "user.miner2"
    threshold: 3000000

