reportSchedule: "0 27 17 * * *"
monitorRate: 10 # in seconds
hystrix:
  command:
    # Do not change. MonitorTest tests are dependant on these parameters
    requestWorkers:
      circuitBreaker.requestVolumeThreshold: 2
      circuitBreaker.sleepWindowInMilliseconds: 900
      execution.isolation.thread.timeoutInMilliseconds: 10000
      metrics.rollingStats.timeInMilliseconds: 500
rules:
  - worker: "user.worker1"
    threshold: 3000000
  - worker: "pak1.test"
    threshold: 3000000
