api:
  key: 'key'
  secret: 'secret'
  userId: 'userId'
rules:
  - worker: 'userId.worker1'
    threshold: 123.45
  - worker: 'userId.worker2'
    threshold: 234.3
telegram:
  apiKey: 'apiKey'
  chatId: 'chatId'
checkPeriod: 60 #in seconds
dailyReport:
  hour: 11
  minute: 04